# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainMenu(object):
    def setupUi(self, MainMenu):
        MainMenu.setObjectName("MainMenu")
        MainMenu.resize(1058, 708)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("indeks.jpeg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainMenu.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainMenu)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(-10, 0, 851, 661))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.tableWidget_2 = QtWidgets.QTableWidget(self.tab)
        self.tableWidget_2.setGeometry(QtCore.QRect(10, 10, 561, 601))
        self.tableWidget_2.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableWidget_2.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.tableWidget_2.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectColumns)
        self.tableWidget_2.setObjectName("tableWidget_2")
        self.tableWidget_2.setColumnCount(4)
        self.tableWidget_2.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(3, item)
        self.tableWidget_2.horizontalHeader().setMinimumSectionSize(140)
        self.formLayoutWidget_3 = QtWidgets.QWidget(self.tab)
        self.formLayoutWidget_3.setGeometry(QtCore.QRect(590, 20, 241, 71))
        self.formLayoutWidget_3.setObjectName("formLayoutWidget_3")
        self.formLayout_3 = QtWidgets.QFormLayout(self.formLayoutWidget_3)
        self.formLayout_3.setContentsMargins(0, 0, 0, 0)
        self.formLayout_3.setObjectName("formLayout_3")
        self.billsTable = QtWidgets.QLabel(self.formLayoutWidget_3)
        self.billsTable.setObjectName("billsTable")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.billsTable)
        self.billsTableInput = QtWidgets.QComboBox(self.formLayoutWidget_3)
        self.billsTableInput.setObjectName("billsTableInput")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.billsTableInput)
        self.billsWaiter = QtWidgets.QLabel(self.formLayoutWidget_3)
        self.billsWaiter.setObjectName("billsWaiter")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.billsWaiter)
        self.billsWaiterInput = QtWidgets.QComboBox(self.formLayoutWidget_3)
        self.billsWaiterInput.setObjectName("billsWaiterInput")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.billsWaiterInput)
        self.billAddButton = QtWidgets.QPushButton(self.tab)
        self.billAddButton.setGeometry(QtCore.QRect(580, 100, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.billAddButton.setFont(font)
        self.billAddButton.setObjectName("billAddButton")
        self.billDeleteButton = QtWidgets.QPushButton(self.tab)
        self.billDeleteButton.setGeometry(QtCore.QRect(720, 150, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.billDeleteButton.setFont(font)
        self.billDeleteButton.setObjectName("billDeleteButton")
        self.billDetailsButton = QtWidgets.QPushButton(self.tab)
        self.billDetailsButton.setGeometry(QtCore.QRect(720, 100, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.billDetailsButton.setFont(font)
        self.billDetailsButton.setObjectName("billDetailsButton")
        self.billEditButton = QtWidgets.QPushButton(self.tab)
        self.billEditButton.setGeometry(QtCore.QRect(580, 150, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.billEditButton.setFont(font)
        self.billEditButton.setObjectName("billEditButton")
        self.line_2 = QtWidgets.QFrame(self.tab)
        self.line_2.setGeometry(QtCore.QRect(570, 240, 281, 16))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.billsProductTable = QtWidgets.QTableWidget(self.tab)
        self.billsProductTable.setGeometry(QtCore.QRect(580, 260, 256, 241))
        self.billsProductTable.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.billsProductTable.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.billsProductTable.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.billsProductTable.setObjectName("billsProductTable")
        self.billsProductTable.setColumnCount(4)
        self.billsProductTable.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.billsProductTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.billsProductTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.billsProductTable.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.billsProductTable.setHorizontalHeaderItem(3, item)
        self.billsProductTable.horizontalHeader().setDefaultSectionSize(63)
        self.formLayoutWidget_4 = QtWidgets.QWidget(self.tab)
        self.formLayoutWidget_4.setGeometry(QtCore.QRect(590, 510, 241, 71))
        self.formLayoutWidget_4.setObjectName("formLayoutWidget_4")
        self.formLayout_4 = QtWidgets.QFormLayout(self.formLayoutWidget_4)
        self.formLayout_4.setContentsMargins(0, 0, 0, 0)
        self.formLayout_4.setObjectName("formLayout_4")
        self.billsProductName = QtWidgets.QLabel(self.formLayoutWidget_4)
        self.billsProductName.setObjectName("billsProductName")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.billsProductName)
        self.billsProductNameInput = QtWidgets.QComboBox(self.formLayoutWidget_4)
        self.billsProductNameInput.setObjectName("billsProductNameInput")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.billsProductNameInput)
        self.billsProductQuantity = QtWidgets.QLabel(self.formLayoutWidget_4)
        self.billsProductQuantity.setObjectName("billsProductQuantity")
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.billsProductQuantity)
        self.billsProductQuantityInput = QtWidgets.QSpinBox(self.formLayoutWidget_4)
        self.billsProductQuantityInput.setObjectName("billsProductQuantityInput")
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.billsProductQuantityInput)
        self.billProductAddButton_2 = QtWidgets.QPushButton(self.tab)
        self.billProductAddButton_2.setGeometry(QtCore.QRect(590, 590, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.billProductAddButton_2.setFont(font)
        self.billProductAddButton_2.setObjectName("billProductAddButton_2")
        self.billProductRemoveButton = QtWidgets.QPushButton(self.tab)
        self.billProductRemoveButton.setGeometry(QtCore.QRect(720, 590, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.billProductRemoveButton.setFont(font)
        self.billProductRemoveButton.setObjectName("billProductRemoveButton")
        self.billFinalizeButton = QtWidgets.QPushButton(self.tab)
        self.billFinalizeButton.setGeometry(QtCore.QRect(580, 200, 261, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.billFinalizeButton.setFont(font)
        self.billFinalizeButton.setObjectName("billFinalizeButton")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.productsTable = QtWidgets.QTableWidget(self.tab_2)
        self.productsTable.setGeometry(QtCore.QRect(10, 10, 501, 591))
        self.productsTable.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.productsTable.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.productsTable.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.productsTable.setObjectName("productsTable")
        self.productsTable.setColumnCount(3)
        self.productsTable.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.productsTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.productsTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.productsTable.setHorizontalHeaderItem(2, item)
        self.productsTable.horizontalHeader().setDefaultSectionSize(166)
        self.formLayoutWidget_2 = QtWidgets.QWidget(self.tab_2)
        self.formLayoutWidget_2.setGeometry(QtCore.QRect(530, 20, 301, 101))
        self.formLayoutWidget_2.setObjectName("formLayoutWidget_2")
        self.formLayout_2 = QtWidgets.QFormLayout(self.formLayoutWidget_2)
        self.formLayout_2.setContentsMargins(0, 0, 0, 0)
        self.formLayout_2.setObjectName("formLayout_2")
        self.productName = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.productName.setObjectName("productName")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.productName)
        self.productNameInput = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.productNameInput.setObjectName("productNameInput")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.productNameInput)
        self.productDescription = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.productDescription.setObjectName("productDescription")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.productDescription)
        self.productDescriptionInput = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.productDescriptionInput.setObjectName("productDescriptionInput")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.productDescriptionInput)
        self.productPrice = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.productPrice.setObjectName("productPrice")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.productPrice)
        self.productPriceInput = QtWidgets.QDoubleSpinBox(self.formLayoutWidget_2)
        self.productPriceInput.setObjectName("productPriceInput")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.productPriceInput)
        self.productAddButton = QtWidgets.QPushButton(self.tab_2)
        self.productAddButton.setGeometry(QtCore.QRect(520, 140, 151, 61))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.productAddButton.setFont(font)
        self.productAddButton.setObjectName("productAddButton")
        self.productCardButton = QtWidgets.QPushButton(self.tab_2)
        self.productCardButton.setGeometry(QtCore.QRect(680, 140, 151, 61))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.productCardButton.setFont(font)
        self.productCardButton.setObjectName("productCardButton")
        self.productEditButton = QtWidgets.QPushButton(self.tab_2)
        self.productEditButton.setGeometry(QtCore.QRect(520, 210, 151, 61))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.productEditButton.setFont(font)
        self.productEditButton.setObjectName("productEditButton")
        self.productDeleteButton = QtWidgets.QPushButton(self.tab_2)
        self.productDeleteButton.setGeometry(QtCore.QRect(680, 210, 151, 61))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.productDeleteButton.setFont(font)
        self.productDeleteButton.setObjectName("productDeleteButton")
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.tablesTable = QtWidgets.QTableWidget(self.tab_3)
        self.tablesTable.setGeometry(QtCore.QRect(10, 40, 581, 521))
        self.tablesTable.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tablesTable.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.tablesTable.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tablesTable.setColumnCount(1)
        self.tablesTable.setObjectName("tablesTable")
        self.tablesTable.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tablesTable.setHorizontalHeaderItem(0, item)
        self.tablesTable.horizontalHeader().setDefaultSectionSize(579)
        self.tableAddButton = QtWidgets.QPushButton(self.tab_3)
        self.tableAddButton.setGeometry(QtCore.QRect(620, 160, 221, 61))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.tableAddButton.setFont(font)
        self.tableAddButton.setObjectName("tableAddButton")
        self.tableDeleteButton = QtWidgets.QPushButton(self.tab_3)
        self.tableDeleteButton.setGeometry(QtCore.QRect(620, 230, 221, 61))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.tableDeleteButton.setFont(font)
        self.tableDeleteButton.setObjectName("tableDeleteButton")
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.waitersTable = QtWidgets.QTableWidget(self.tab_5)
        self.waitersTable.setGeometry(QtCore.QRect(10, 30, 570, 581))
        self.waitersTable.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.waitersTable.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.waitersTable.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.waitersTable.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.waitersTable.setColumnCount(3)
        self.waitersTable.setObjectName("waitersTable")
        self.waitersTable.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.waitersTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.waitersTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.waitersTable.setHorizontalHeaderItem(2, item)
        self.waitersTable.horizontalHeader().setCascadingSectionResizes(True)
        self.waitersTable.horizontalHeader().setDefaultSectionSize(189)
        self.waitersTable.horizontalHeader().setStretchLastSection(False)
        self.formLayoutWidget = QtWidgets.QWidget(self.tab_5)
        self.formLayoutWidget.setGeometry(QtCore.QRect(590, 30, 251, 71))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.waiterName = QtWidgets.QLabel(self.formLayoutWidget)
        self.waiterName.setObjectName("waiterName")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.waiterName)
        self.waiterNameInput = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.waiterNameInput.setObjectName("waiterNameInput")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.waiterNameInput)
        self.waiterSurname = QtWidgets.QLabel(self.formLayoutWidget)
        self.waiterSurname.setObjectName("waiterSurname")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.waiterSurname)
        self.waiterSurnameInput = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.waiterSurnameInput.setObjectName("waiterSurnameInput")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.waiterSurnameInput)
        self.waiterAddButton = QtWidgets.QPushButton(self.tab_5)
        self.waiterAddButton.setGeometry(QtCore.QRect(590, 110, 251, 61))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.waiterAddButton.setFont(font)
        self.waiterAddButton.setObjectName("waiterAddButton")
        self.waiterEditButton = QtWidgets.QPushButton(self.tab_5)
        self.waiterEditButton.setGeometry(QtCore.QRect(590, 180, 251, 61))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.waiterEditButton.setFont(font)
        self.waiterEditButton.setObjectName("waiterEditButton")
        self.waiterDeleteButton = QtWidgets.QPushButton(self.tab_5)
        self.waiterDeleteButton.setGeometry(QtCore.QRect(590, 250, 251, 60))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.waiterDeleteButton.setFont(font)
        self.waiterDeleteButton.setObjectName("waiterDeleteButton")
        self.revenueButton = QtWidgets.QPushButton(self.tab_5)
        self.revenueButton.setGeometry(QtCore.QRect(580, 490, 251, 61))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.revenueButton.setFont(font)
        self.revenueButton.setObjectName("revenueButton")
        self.line = QtWidgets.QFrame(self.tab_5)
        self.line.setGeometry(QtCore.QRect(580, 330, 271, 20))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.label_2 = QtWidgets.QLabel(self.tab_5)
        self.label_2.setGeometry(QtCore.QRect(600, 350, 231, 31))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.tab_5)
        self.label_3.setGeometry(QtCore.QRect(640, 380, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.daysBackInput = QtWidgets.QSpinBox(self.tab_5)
        self.daysBackInput.setGeometry(QtCore.QRect(700, 440, 121, 26))
        self.daysBackInput.setObjectName("daysBackInput")
        self.daysBack = QtWidgets.QLabel(self.tab_5)
        self.daysBack.setGeometry(QtCore.QRect(590, 440, 101, 26))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.daysBack.setFont(font)
        self.daysBack.setObjectName("daysBack")
        self.tabWidget.addTab(self.tab_5, "")
        self.title = QtWidgets.QLabel(self.centralwidget)
        self.title.setGeometry(QtCore.QRect(860, 10, 181, 101))
        self.title.setObjectName("title")
        self.exitButton = QtWidgets.QPushButton(self.centralwidget)
        self.exitButton.setGeometry(QtCore.QRect(860, 550, 191, 61))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.exitButton.setFont(font)
        self.exitButton.setObjectName("exitButton")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(860, 360, 213, 171))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.freeTablesNumber = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.freeTablesNumber.setFont(font)
        self.freeTablesNumber.setObjectName("freeTablesNumber")
        self.gridLayout.addWidget(self.freeTablesNumber, 2, 1, 1, 1)
        self.waiters = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.waiters.setFont(font)
        self.waiters.setObjectName("waiters")
        self.gridLayout.addWidget(self.waiters, 0, 0, 1, 1)
        self.waitersNumber = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.waitersNumber.setFont(font)
        self.waitersNumber.setObjectName("waitersNumber")
        self.gridLayout.addWidget(self.waitersNumber, 0, 1, 1, 1)
        self.freeTables = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.freeTables.setFont(font)
        self.freeTables.setObjectName("freeTables")
        self.gridLayout.addWidget(self.freeTables, 2, 0, 1, 1)
        self.openBills = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.openBills.setFont(font)
        self.openBills.setObjectName("openBills")
        self.gridLayout.addWidget(self.openBills, 3, 0, 1, 1)
        self.productsNumber = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.productsNumber.setFont(font)
        self.productsNumber.setObjectName("productsNumber")
        self.gridLayout.addWidget(self.productsNumber, 1, 1, 1, 1)
        self.openBillsNumber = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.openBillsNumber.setFont(font)
        self.openBillsNumber.setObjectName("openBillsNumber")
        self.gridLayout.addWidget(self.openBillsNumber, 3, 1, 1, 1)
        self.products = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.products.setFont(font)
        self.products.setObjectName("products")
        self.gridLayout.addWidget(self.products, 1, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(860, 120, 191, 221))
        self.label.setStyleSheet("background-image: url(:/nowyPrzedrostek/rattie.jpg);")
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(":/nowyPrzedrostek/rattie.jpg"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        MainMenu.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainMenu)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1058, 22))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainMenu.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainMenu)
        self.statusbar.setObjectName("statusbar")
        MainMenu.setStatusBar(self.statusbar)
        self.actionExit = QtWidgets.QAction(MainMenu)
        self.actionExit.setObjectName("actionExit")
        self.menuFile.addAction(self.actionExit)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainMenu)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainMenu)

    def retranslateUi(self, MainMenu):
        _translate = QtCore.QCoreApplication.translate
        MainMenu.setWindowTitle(_translate("MainMenu", "Restaurant Management System"))
        item = self.tableWidget_2.horizontalHeaderItem(0)
        item.setText(_translate("MainMenu", "ID"))
        item = self.tableWidget_2.horizontalHeaderItem(1)
        item.setText(_translate("MainMenu", "Table"))
        item = self.tableWidget_2.horizontalHeaderItem(2)
        item.setText(_translate("MainMenu", "Waiter"))
        item = self.tableWidget_2.horizontalHeaderItem(3)
        item.setText(_translate("MainMenu", "Amount"))
        self.billsTable.setText(_translate("MainMenu", "Table:"))
        self.billsWaiter.setText(_translate("MainMenu", "Waiter:"))
        self.billAddButton.setText(_translate("MainMenu", "ADD"))
        self.billDeleteButton.setText(_translate("MainMenu", "DELETE"))
        self.billDetailsButton.setText(_translate("MainMenu", "DETAILS"))
        self.billEditButton.setText(_translate("MainMenu", "EDIT"))
        item = self.billsProductTable.horizontalHeaderItem(0)
        item.setText(_translate("MainMenu", "ID"))
        item = self.billsProductTable.horizontalHeaderItem(1)
        item.setText(_translate("MainMenu", "Name"))
        item = self.billsProductTable.horizontalHeaderItem(2)
        item.setText(_translate("MainMenu", "Quantity"))
        item = self.billsProductTable.horizontalHeaderItem(3)
        item.setText(_translate("MainMenu", "Sum"))
        self.billsProductName.setText(_translate("MainMenu", "Product:"))
        self.billsProductQuantity.setText(_translate("MainMenu", "Quantity:"))
        self.billProductAddButton_2.setText(_translate("MainMenu", "ADD"))
        self.billProductRemoveButton.setText(_translate("MainMenu", "REMOVE"))
        self.billFinalizeButton.setText(_translate("MainMenu", "FINALIZE"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainMenu", "Bills"))
        item = self.productsTable.horizontalHeaderItem(0)
        item.setText(_translate("MainMenu", "ID"))
        item = self.productsTable.horizontalHeaderItem(1)
        item.setText(_translate("MainMenu", "Name"))
        item = self.productsTable.horizontalHeaderItem(2)
        item.setText(_translate("MainMenu", "Price"))
        self.productName.setText(_translate("MainMenu", "Name:"))
        self.productDescription.setText(_translate("MainMenu", "Description:"))
        self.productPrice.setText(_translate("MainMenu", "Price:"))
        self.productAddButton.setText(_translate("MainMenu", "ADD"))
        self.productCardButton.setText(_translate("MainMenu", "CARD"))
        self.productEditButton.setText(_translate("MainMenu", "EDIT"))
        self.productDeleteButton.setText(_translate("MainMenu", "DELETE"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainMenu", "Menu"))
        item = self.tablesTable.horizontalHeaderItem(0)
        item.setText(_translate("MainMenu", "ID"))
        self.tableAddButton.setText(_translate("MainMenu", "ADD"))
        self.tableDeleteButton.setText(_translate("MainMenu", "DELETE"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainMenu", "Tables"))
        self.waitersTable.setSortingEnabled(True)
        item = self.waitersTable.horizontalHeaderItem(0)
        item.setText(_translate("MainMenu", "ID"))
        item = self.waitersTable.horizontalHeaderItem(1)
        item.setText(_translate("MainMenu", "Name"))
        item = self.waitersTable.horizontalHeaderItem(2)
        item.setText(_translate("MainMenu", "Surname"))
        self.waiterName.setText(_translate("MainMenu", "Name:"))
        self.waiterSurname.setText(_translate("MainMenu", "Surname:"))
        self.waiterAddButton.setText(_translate("MainMenu", "ADD"))
        self.waiterEditButton.setText(_translate("MainMenu", "EDIT"))
        self.waiterDeleteButton.setText(_translate("MainMenu", "DELETE"))
        self.revenueButton.setText(_translate("MainMenu", "CALCULATE"))
        self.label_2.setText(_translate("MainMenu", "WAITER\'S REVENUE"))
        self.label_3.setText(_translate("MainMenu", "PER PERIOD"))
        self.daysBack.setText(_translate("MainMenu", "Days back:"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), _translate("MainMenu", "Waiters"))
        self.title.setText(_translate("MainMenu", "<html><head/><body><p><span style=\" font-size:20pt;\">Restaurant<br/>Manager</span></p><p><span style=\" font-size:14pt;\">by Mateusz Gieroba</span></p></body></html>"))
        self.exitButton.setText(_translate("MainMenu", "EXIT"))
        self.freeTablesNumber.setText(_translate("MainMenu", "TextLabel"))
        self.waiters.setText(_translate("MainMenu", "Waiters:"))
        self.waitersNumber.setText(_translate("MainMenu", "TextLabel"))
        self.freeTables.setText(_translate("MainMenu", "Free tables:"))
        self.openBills.setText(_translate("MainMenu", "Open bills:"))
        self.productsNumber.setText(_translate("MainMenu", "TextLabel"))
        self.openBillsNumber.setText(_translate("MainMenu", "TextLabel"))
        self.products.setText(_translate("MainMenu", "Products:"))
        self.menuFile.setTitle(_translate("MainMenu", "File"))
        self.actionExit.setText(_translate("MainMenu", "Exit"))
import logo_rc
