# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainMenu(object):
    def setupUi(self, MainMenu):
        MainMenu.setObjectName("MainMenu")
        MainMenu.resize(1058, 708)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("indeks.jpeg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainMenu.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainMenu)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 851, 661))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.tablesTable = QtWidgets.QTableWidget(self.tab_3)
        self.tablesTable.setGeometry(QtCore.QRect(10, 40, 581, 521))
        self.tablesTable.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tablesTable.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.tablesTable.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tablesTable.setColumnCount(1)
        self.tablesTable.setObjectName("tablesTable")
        self.tablesTable.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tablesTable.setHorizontalHeaderItem(0, item)
        self.tablesTable.horizontalHeader().setDefaultSectionSize(579)
        self.tableAddButton = QtWidgets.QPushButton(self.tab_3)
        self.tableAddButton.setGeometry(QtCore.QRect(620, 160, 221, 61))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.tableAddButton.setFont(font)
        self.tableAddButton.setObjectName("tableAddButton")
        self.tableDeleteButton = QtWidgets.QPushButton(self.tab_3)
        self.tableDeleteButton.setGeometry(QtCore.QRect(620, 230, 221, 61))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.tableDeleteButton.setFont(font)
        self.tableDeleteButton.setObjectName("tableDeleteButton")
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.waitersTable = QtWidgets.QTableWidget(self.tab_5)
        self.waitersTable.setGeometry(QtCore.QRect(10, 30, 570, 581))
        self.waitersTable.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.waitersTable.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.waitersTable.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.waitersTable.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.waitersTable.setColumnCount(3)
        self.waitersTable.setObjectName("waitersTable")
        self.waitersTable.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.waitersTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.waitersTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.waitersTable.setHorizontalHeaderItem(2, item)
        self.waitersTable.horizontalHeader().setCascadingSectionResizes(True)
        self.waitersTable.horizontalHeader().setDefaultSectionSize(189)
        self.waitersTable.horizontalHeader().setStretchLastSection(False)
        self.formLayoutWidget = QtWidgets.QWidget(self.tab_5)
        self.formLayoutWidget.setGeometry(QtCore.QRect(590, 30, 251, 71))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.waiterName = QtWidgets.QLabel(self.formLayoutWidget)
        self.waiterName.setObjectName("waiterName")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.waiterName)
        self.waiterNameInput = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.waiterNameInput.setObjectName("waiterNameInput")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.waiterNameInput)
        self.waiterSurname = QtWidgets.QLabel(self.formLayoutWidget)
        self.waiterSurname.setObjectName("waiterSurname")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.waiterSurname)
        self.waiterSurnameInput = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.waiterSurnameInput.setObjectName("waiterSurnameInput")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.waiterSurnameInput)
        self.waiterAddButton = QtWidgets.QPushButton(self.tab_5)
        self.waiterAddButton.setGeometry(QtCore.QRect(590, 110, 251, 61))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.waiterAddButton.setFont(font)
        self.waiterAddButton.setObjectName("waiterAddButton")
        self.waiterEditButton = QtWidgets.QPushButton(self.tab_5)
        self.waiterEditButton.setGeometry(QtCore.QRect(590, 180, 251, 61))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.waiterEditButton.setFont(font)
        self.waiterEditButton.setObjectName("waiterEditButton")
        self.waiterDeleteButton = QtWidgets.QPushButton(self.tab_5)
        self.waiterDeleteButton.setGeometry(QtCore.QRect(590, 250, 251, 60))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.waiterDeleteButton.setFont(font)
        self.waiterDeleteButton.setObjectName("waiterDeleteButton")
        self.revenueButton = QtWidgets.QPushButton(self.tab_5)
        self.revenueButton.setGeometry(QtCore.QRect(590, 550, 251, 61))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.revenueButton.setFont(font)
        self.revenueButton.setObjectName("revenueButton")
        self.revenueDateBegin = QtWidgets.QDateTimeEdit(self.tab_5)
        self.revenueDateBegin.setGeometry(QtCore.QRect(590, 420, 251, 51))
        self.revenueDateBegin.setCalendarPopup(True)
        self.revenueDateBegin.setObjectName("revenueDateBegin")
        self.revenueDateEnd = QtWidgets.QDateTimeEdit(self.tab_5)
        self.revenueDateEnd.setGeometry(QtCore.QRect(590, 480, 251, 51))
        self.revenueDateEnd.setCalendarPopup(True)
        self.revenueDateEnd.setObjectName("revenueDateEnd")
        self.line = QtWidgets.QFrame(self.tab_5)
        self.line.setGeometry(QtCore.QRect(580, 330, 271, 20))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.label_2 = QtWidgets.QLabel(self.tab_5)
        self.label_2.setGeometry(QtCore.QRect(600, 350, 231, 31))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.tab_5)
        self.label_3.setGeometry(QtCore.QRect(640, 380, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.tabWidget.addTab(self.tab_5, "")
        self.title = QtWidgets.QLabel(self.centralwidget)
        self.title.setGeometry(QtCore.QRect(860, 10, 181, 101))
        self.title.setObjectName("title")
        self.exitButton = QtWidgets.QPushButton(self.centralwidget)
        self.exitButton.setGeometry(QtCore.QRect(860, 550, 191, 61))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.exitButton.setFont(font)
        self.exitButton.setObjectName("exitButton")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(860, 360, 213, 171))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.freeTablesNumber = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.freeTablesNumber.setFont(font)
        self.freeTablesNumber.setObjectName("freeTablesNumber")
        self.gridLayout.addWidget(self.freeTablesNumber, 2, 1, 1, 1)
        self.waiters = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.waiters.setFont(font)
        self.waiters.setObjectName("waiters")
        self.gridLayout.addWidget(self.waiters, 0, 0, 1, 1)
        self.waitersNumber = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.waitersNumber.setFont(font)
        self.waitersNumber.setObjectName("waitersNumber")
        self.gridLayout.addWidget(self.waitersNumber, 0, 1, 1, 1)
        self.freeTables = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.freeTables.setFont(font)
        self.freeTables.setObjectName("freeTables")
        self.gridLayout.addWidget(self.freeTables, 2, 0, 1, 1)
        self.openBills = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.openBills.setFont(font)
        self.openBills.setObjectName("openBills")
        self.gridLayout.addWidget(self.openBills, 3, 0, 1, 1)
        self.productsNumber = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.productsNumber.setFont(font)
        self.productsNumber.setObjectName("productsNumber")
        self.gridLayout.addWidget(self.productsNumber, 1, 1, 1, 1)
        self.openBillsNumber = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.openBillsNumber.setFont(font)
        self.openBillsNumber.setObjectName("openBillsNumber")
        self.gridLayout.addWidget(self.openBillsNumber, 3, 1, 1, 1)
        self.products = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.products.setFont(font)
        self.products.setObjectName("products")
        self.gridLayout.addWidget(self.products, 1, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(860, 120, 191, 221))
        self.label.setStyleSheet("background-image: url(:/nowyPrzedrostek/rattie.jpg);")
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(":/nowyPrzedrostek/rattie.jpg"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        MainMenu.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainMenu)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1058, 22))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainMenu.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainMenu)
        self.statusbar.setObjectName("statusbar")
        MainMenu.setStatusBar(self.statusbar)
        self.actionExit = QtWidgets.QAction(MainMenu)
        self.actionExit.setObjectName("actionExit")
        self.menuFile.addAction(self.actionExit)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainMenu)
        self.tabWidget.setCurrentIndex(3)
        QtCore.QMetaObject.connectSlotsByName(MainMenu)

    def retranslateUi(self, MainMenu):
        _translate = QtCore.QCoreApplication.translate
        MainMenu.setWindowTitle(_translate("MainMenu", "Restaurant Management System"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainMenu", "Bills"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainMenu", "Menu"))
        item = self.tablesTable.horizontalHeaderItem(0)
        item.setText(_translate("MainMenu", "ID"))
        self.tableAddButton.setText(_translate("MainMenu", "ADD"))
        self.tableDeleteButton.setText(_translate("MainMenu", "DELETE"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainMenu", "Tables"))
        self.waitersTable.setSortingEnabled(True)
        item = self.waitersTable.horizontalHeaderItem(0)
        item.setText(_translate("MainMenu", "ID"))
        item = self.waitersTable.horizontalHeaderItem(1)
        item.setText(_translate("MainMenu", "Name"))
        item = self.waitersTable.horizontalHeaderItem(2)
        item.setText(_translate("MainMenu", "Surname"))
        self.waiterName.setText(_translate("MainMenu", "Name:"))
        self.waiterSurname.setText(_translate("MainMenu", "Surname:"))
        self.waiterAddButton.setText(_translate("MainMenu", "ADD"))
        self.waiterEditButton.setText(_translate("MainMenu", "EDIT"))
        self.waiterDeleteButton.setText(_translate("MainMenu", "DELETE"))
        self.revenueButton.setText(_translate("MainMenu", "CALCULATE"))
        self.label_2.setText(_translate("MainMenu", "WAITER\'S REVENUE"))
        self.label_3.setText(_translate("MainMenu", "PER PERIOD"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), _translate("MainMenu", "Waiters"))
        self.title.setText(_translate("MainMenu", "<html><head/><body><p><span style=\" font-size:20pt;\">Restaurant<br/>Manager</span></p><p><span style=\" font-size:14pt;\">by Mateusz Gieroba</span></p></body></html>"))
        self.exitButton.setText(_translate("MainMenu", "EXIT"))
        self.freeTablesNumber.setText(_translate("MainMenu", "TextLabel"))
        self.waiters.setText(_translate("MainMenu", "Waiters:"))
        self.waitersNumber.setText(_translate("MainMenu", "TextLabel"))
        self.freeTables.setText(_translate("MainMenu", "Free tables:"))
        self.openBills.setText(_translate("MainMenu", "Open bills:"))
        self.productsNumber.setText(_translate("MainMenu", "TextLabel"))
        self.openBillsNumber.setText(_translate("MainMenu", "TextLabel"))
        self.products.setText(_translate("MainMenu", "Products:"))
        self.menuFile.setTitle(_translate("MainMenu", "File"))
        self.actionExit.setText(_translate("MainMenu", "Exit"))
import logo_rc
