# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainMenu(object):
    def setupUi(self, MainMenu):
        MainMenu.setObjectName("MainMenu")
        MainMenu.resize(1058, 708)
        self.centralwidget = QtWidgets.QWidget(MainMenu)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 851, 661))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.tableView = QtWidgets.QTableView(self.tab)
        self.tableView.setGeometry(QtCore.QRect(10, 20, 561, 561))
        self.tableView.setObjectName("tableView")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.tabWidget.addTab(self.tab_4, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.waitersTable = QtWidgets.QTableWidget(self.tab_5)
        self.waitersTable.setGeometry(QtCore.QRect(10, 20, 571, 581))
        self.waitersTable.setObjectName("waitersTable")
        self.waitersTable.setColumnCount(0)
        self.waitersTable.setRowCount(0)
        self.formLayoutWidget = QtWidgets.QWidget(self.tab_5)
        self.formLayoutWidget.setGeometry(QtCore.QRect(590, 30, 251, 71))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.waiterName = QtWidgets.QLabel(self.formLayoutWidget)
        self.waiterName.setObjectName("waiterName")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.waiterName)
        self.waiterNameInput = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.waiterNameInput.setObjectName("waiterNameInput")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.waiterNameInput)
        self.waiterSurname = QtWidgets.QLabel(self.formLayoutWidget)
        self.waiterSurname.setObjectName("waiterSurname")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.waiterSurname)
        self.waiterSurnameInput = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.waiterSurnameInput.setObjectName("waiterSurnameInput")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.waiterSurnameInput)
        self.waiterAddButton = QtWidgets.QPushButton(self.tab_5)
        self.waiterAddButton.setGeometry(QtCore.QRect(590, 110, 251, 61))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.waiterAddButton.setFont(font)
        self.waiterAddButton.setObjectName("waiterAddButton")
        self.waiterEditButton = QtWidgets.QPushButton(self.tab_5)
        self.waiterEditButton.setGeometry(QtCore.QRect(590, 180, 251, 61))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.waiterEditButton.setFont(font)
        self.waiterEditButton.setObjectName("waiterEditButton")
        self.waiterDeleteButton = QtWidgets.QPushButton(self.tab_5)
        self.waiterDeleteButton.setGeometry(QtCore.QRect(590, 250, 251, 61))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.waiterDeleteButton.setFont(font)
        self.waiterDeleteButton.setObjectName("waiterDeleteButton")
        self.revenueButton = QtWidgets.QPushButton(self.tab_5)
        self.revenueButton.setGeometry(QtCore.QRect(590, 540, 251, 61))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.revenueButton.setFont(font)
        self.revenueButton.setObjectName("revenueButton")
        self.revenueDateBegin = QtWidgets.QDateTimeEdit(self.tab_5)
        self.revenueDateBegin.setGeometry(QtCore.QRect(590, 430, 251, 41))
        self.revenueDateBegin.setObjectName("revenueDateBegin")
        self.revenueDateEnd = QtWidgets.QDateTimeEdit(self.tab_5)
        self.revenueDateEnd.setGeometry(QtCore.QRect(590, 480, 251, 41))
        self.revenueDateEnd.setObjectName("revenueDateEnd")
        self.waitersNameAndSurname = QtWidgets.QLabel(self.tab_5)
        self.waitersNameAndSurname.setGeometry(QtCore.QRect(590, 360, 241, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.waitersNameAndSurname.setFont(font)
        self.waitersNameAndSurname.setObjectName("waitersNameAndSurname")
        self.line = QtWidgets.QFrame(self.tab_5)
        self.line.setGeometry(QtCore.QRect(580, 340, 271, 20))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.tabWidget.addTab(self.tab_5, "")
        self.krticko = QtWidgets.QGraphicsView(self.centralwidget)
        self.krticko.setGeometry(QtCore.QRect(860, 110, 191, 241))
        self.krticko.setObjectName("krticko")
        self.waiters = QtWidgets.QLabel(self.centralwidget)
        self.waiters.setGeometry(QtCore.QRect(860, 370, 81, 21))
        self.waiters.setObjectName("waiters")
        self.title = QtWidgets.QLabel(self.centralwidget)
        self.title.setGeometry(QtCore.QRect(860, 10, 181, 91))
        self.title.setObjectName("title")
        self.waitersNumber = QtWidgets.QLabel(self.centralwidget)
        self.waitersNumber.setGeometry(QtCore.QRect(970, 370, 91, 31))
        self.waitersNumber.setObjectName("waitersNumber")
        self.products = QtWidgets.QLabel(self.centralwidget)
        self.products.setGeometry(QtCore.QRect(860, 400, 91, 21))
        self.products.setObjectName("products")
        self.productsNumber = QtWidgets.QLabel(self.centralwidget)
        self.productsNumber.setGeometry(QtCore.QRect(970, 400, 91, 31))
        self.productsNumber.setObjectName("productsNumber")
        self.openBills = QtWidgets.QLabel(self.centralwidget)
        self.openBills.setGeometry(QtCore.QRect(860, 430, 111, 31))
        self.openBills.setObjectName("openBills")
        self.openBillsNumber = QtWidgets.QLabel(self.centralwidget)
        self.openBillsNumber.setGeometry(QtCore.QRect(970, 430, 91, 31))
        self.openBillsNumber.setObjectName("openBillsNumber")
        self.freeTables = QtWidgets.QLabel(self.centralwidget)
        self.freeTables.setGeometry(QtCore.QRect(860, 460, 111, 31))
        self.freeTables.setObjectName("freeTables")
        self.freeTablesNumber = QtWidgets.QLabel(self.centralwidget)
        self.freeTablesNumber.setGeometry(QtCore.QRect(980, 460, 91, 31))
        self.freeTablesNumber.setObjectName("freeTablesNumber")
        self.bookings = QtWidgets.QLabel(self.centralwidget)
        self.bookings.setGeometry(QtCore.QRect(860, 490, 111, 31))
        self.bookings.setObjectName("bookings")
        self.bookingsNumber = QtWidgets.QLabel(self.centralwidget)
        self.bookingsNumber.setGeometry(QtCore.QRect(980, 490, 91, 31))
        self.bookingsNumber.setObjectName("bookingsNumber")
        self.exitButton = QtWidgets.QPushButton(self.centralwidget)
        self.exitButton.setGeometry(QtCore.QRect(860, 550, 191, 61))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.exitButton.setFont(font)
        self.exitButton.setObjectName("exitButton")
        self.tabWidget.raise_()
        self.krticko.raise_()
        self.waiters.raise_()
        self.title.raise_()
        self.waitersNumber.raise_()
        self.products.raise_()
        self.productsNumber.raise_()
        self.openBillsNumber.raise_()
        self.openBills.raise_()
        self.freeTables.raise_()
        self.freeTablesNumber.raise_()
        self.bookings.raise_()
        self.bookingsNumber.raise_()
        self.exitButton.raise_()
        MainMenu.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainMenu)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1058, 22))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainMenu.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainMenu)
        self.statusbar.setObjectName("statusbar")
        MainMenu.setStatusBar(self.statusbar)
        self.actionExit = QtWidgets.QAction(MainMenu)
        self.actionExit.setObjectName("actionExit")
        self.menuFile.addAction(self.actionExit)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainMenu)
        self.tabWidget.setCurrentIndex(4)
        QtCore.QMetaObject.connectSlotsByName(MainMenu)

    def retranslateUi(self, MainMenu):
        _translate = QtCore.QCoreApplication.translate
        MainMenu.setWindowTitle(_translate("MainMenu", "MainWindow"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainMenu", "Bills"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainMenu", "Menu"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainMenu", "Bookings"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("MainMenu", "Ingredients"))
        self.waiterName.setText(_translate("MainMenu", "Name:"))
        self.waiterSurname.setText(_translate("MainMenu", "Surname:"))
        self.waiterAddButton.setText(_translate("MainMenu", "ADD"))
        self.waiterEditButton.setText(_translate("MainMenu", "EDIT"))
        self.waiterDeleteButton.setText(_translate("MainMenu", "DELETE"))
        self.revenueButton.setText(_translate("MainMenu", "REVENUE"))
        self.waitersNameAndSurname.setText(_translate("MainMenu", "NAME AND SURNAME"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), _translate("MainMenu", "Waiters"))
        self.waiters.setText(_translate("MainMenu", "<html><head/><body><p><span style=\" font-size:16pt;\">Waiters:</span></p></body></html>"))
        self.title.setText(_translate("MainMenu", "<html><head/><body><p><span style=\" font-size:20pt;\">Restaurant<br/>Management<br/>System</span></p></body></html>"))
        self.waitersNumber.setText(_translate("MainMenu", "<html><head/><body><p><span style=\" font-size:16pt;\">TextLabel</span></p></body></html>"))
        self.products.setText(_translate("MainMenu", "<html><head/><body><p><span style=\" font-size:16pt;\">Products:</span></p><p><br/></p></body></html>"))
        self.productsNumber.setText(_translate("MainMenu", "<html><head/><body><p><span style=\" font-size:16pt;\">TextLabel</span></p></body></html>"))
        self.openBills.setText(_translate("MainMenu", "<html><head/><body><p><span style=\" font-size:16pt;\">Open bills:</span></p></body></html>"))
        self.openBillsNumber.setText(_translate("MainMenu", "<html><head/><body><p><span style=\" font-size:16pt;\">TextLabel</span></p></body></html>"))
        self.freeTables.setText(_translate("MainMenu", "<html><head/><body><p><span style=\" font-size:16pt;\">Free tables:</span></p></body></html>"))
        self.freeTablesNumber.setText(_translate("MainMenu", "<html><head/><body><p><span style=\" font-size:16pt;\">TextLabel</span></p></body></html>"))
        self.bookings.setText(_translate("MainMenu", "<html><head/><body><p><span style=\" font-size:16pt;\">Bookings:</span></p></body></html>"))
        self.bookingsNumber.setText(_translate("MainMenu", "<html><head/><body><p><span style=\" font-size:16pt;\">TextLabel</span></p></body></html>"))
        self.exitButton.setText(_translate("MainMenu", "EXIT"))
        self.menuFile.setTitle(_translate("MainMenu", "File"))
        self.actionExit.setText(_translate("MainMenu", "Exit"))
